### ISSUE TITLE
TypeError: datetime.time(0, 15) is not JSON serializable

### ISSUE THREAD

**Issue by johnnywell** [pyeve/eve-sqlalchemy#89] opened 2015-11-26 13:46 UTC
I'm having this error when trying to get some objects from a Firebird Database. Is it related to DATE_FORMAT or it should serialize any datetime object?

Following the traceback:
https://gist.github.com/anonymous/fafe8dc7b8d8da14dd24

**Comment by dkellner** [comment] 2017-03-12 07:46
I'm closing this for now as the issue is quite old - sorry for that! If this is still an issue for you (or anyone else) please test against the current master branch and provide a minimal (failing) example.

**Closed by dkellner** 2017-03-12 07:46 UTC
